# Dependabot configuration for automated dependency updates
# Documentation: https://docs.github.com/en/code-security/dependabot

version: 2

updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    target-branch: "dev"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    reviewers:
      - "ox2a-fuu"
    # Group related updates
    groups:
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # npm dependencies (devcontainer CLI, markdownlint, etc.)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    target-branch: "dev"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
      - "automated"
    reviewers:
      - "ox2a-fuu"
    # Ignore major versions that might break things
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    # Group related updates
    groups:
      npm-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Python dependencies (if any requirements.txt or pyproject.toml exists)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 3
    target-branch: "dev"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "automated"
    reviewers:
      - "ox2a-fuu"
