# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'
palette = "ghostty"

# =============================================================================
# Color System - Ghostty Integration
# =============================================================================
# Uses ANSI color names that map directly to your terminal (ghostty) colors
# To sync exact hex values from ghostty: run `sync-ghostty-colors`

# Timeout for starship commands (milliseconds)
command_timeout = 1000

# =============================================================================
# Prompt Format - Smart Context-Aware Two-Line Layout
# =============================================================================
# Left Line 1: [symbol] dir:repo [branch-symbol] status (modified/untracked/staged)
# Left Line 2: ❯ prompt character
# Right: [symbol]dir [branch-symbol] remote:service ⇡ahead⇣behind

format = """
$username\
${custom.context_dir}\
${custom.git_branch_symbol}\
$git_status\
$git_state\
$python\
$rust\
$c\
$docker_context\
$kubernetes\
$cmd_duration
$character"""

# Right-aligned prompt - full git context
right_format = """${custom.context_dir_simple}\
${custom.git_branch_symbol}\
${custom.git_remote_info}\
${custom.git_ahead_behind}"""

# Continuation prompt for multi-line commands (cyan, non-threatening)
continuation_prompt = "[❯❯](bold cyan) "

# =============================================================================
# Custom Modules - Context-Aware Display
# =============================================================================

[custom.context_dir]
command = '''zsh -c 'source ${XDG_CONFIG_HOME:-$HOME/.config}/omz-custom/starship-helpers.zsh && __starship_context_dir' '''
when = "true"
style = "bold cyan"
format = "[$output]($style) "
description = "Context-aware directory display with repo:subdir format"

[custom.context_dir_simple]
command = '''zsh -c 'source ${XDG_CONFIG_HOME:-$HOME/.config}/omz-custom/starship-helpers.zsh && __starship_context_dir_simple' '''
when = "true"
style = "bold cyan"
format = "[$output]($style)"
description = "Simple directory display - basename only for right prompt"

[custom.git_branch_symbol]
command = '''zsh -c 'source ${XDG_CONFIG_HOME:-$HOME/.config}/omz-custom/starship-helpers.zsh && __starship_git_branch_symbol' '''
when = "git rev-parse --git-dir 2>/dev/null"
style = "bold magenta"
format = "[$output]($style)"
description = "Git branch as symbol: [◎] [⎇] [✓] [🔥]"

[custom.git_remote_info]
command = '''zsh -c 'source ${XDG_CONFIG_HOME:-$HOME/.config}/omz-custom/starship-helpers.zsh && __starship_git_remote_info' '''
when = "git rev-parse --git-dir 2>/dev/null"
style = "bold blue"
format = "[$output]($style)"
description = "Git remote info: origin:github, origin:gitlab, local"

[custom.git_ahead_behind]
command = '''zsh -c 'source ${XDG_CONFIG_HOME:-$HOME/.config}/omz-custom/starship-helpers.zsh && __starship_git_ahead_behind' '''
when = "git rev-parse --git-dir 2>/dev/null"
style = "bold yellow"
format = "[$output]($style)"
description = "Git ahead/behind counts: ⇡N⇣M"

# =============================================================================
# Standard Modules Configuration
# =============================================================================

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold bright_black)"
vimcmd_replace_one_symbol = "[❮](bold yellow)"
vimcmd_replace_symbol = "[❮](bold yellow)"
vimcmd_visual_symbol = "[❮](bold magenta)"

[username]
show_always = false
style_user = "bold yellow"
style_root = "bold red"
format = "[$user]($style) "

[git_status]
style = "bold yellow"
format = "[$all_status]($style) "
conflicted = "󰞇"
ahead = ""
behind = ""
diverged = ""
untracked = "?${count}"
stashed = "󰏗${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[git_state]
style = "bold yellow"
format = "[$state( $progress_current/$progress_total)]($style) "
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"

[python]
symbol = " "
style = "bold blue"
format = "[${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"
pyenv_version_name = false
detect_extensions = ["py"]
detect_files = [".python-version", "Pipfile", "pyproject.toml", "requirements.txt", "setup.py", "tox.ini"]
detect_folders = []

[rust]
symbol = " "
style = "bold red"
format = "[$symbol($version )]($style)"
detect_extensions = ["rs"]
detect_files = ["Cargo.toml", "Cargo.lock"]
detect_folders = []

[c]
symbol = " "
style = "bold blue"
format = "[$symbol($version(-$name) )]($style)"
detect_extensions = ["c", "h"]
detect_files = []
detect_folders = []

[docker_context]
symbol = " "
style = "bold blue"
format = "[$symbol$context]($style) "
only_with_files = true
detect_extensions = []
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile", "Containerfile"]
detect_folders = []

[kubernetes]
symbol = "󱃾 "
style = "bold cyan"
format = "[$symbol$context( \\($namespace\\))]($style) "
disabled = false
detect_extensions = []
detect_files = ["k8s", "Dockerfile", "Containerfile"]
detect_folders = ["k8s", "kubernetes"]

[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
"prod.local.cluster.k8s" = "prod"

[cmd_duration]
min_time = 2000
style = "bold yellow"
format = "[󱦟 $duration]($style) "
show_milliseconds = false
show_notifications = false

# Disabled modules (not needed in new design)
[directory]
disabled = true

[git_branch]
disabled = true

[hostname]
disabled = true

[time]
disabled = true

[battery]
disabled = true

[memory_usage]
disabled = true

# =============================================================================
# Ghostty Palette (Generated by sync-ghostty-colors)
# =============================================================================
# Auto-generated from: ghostty +show-config
# Run sync-ghostty-colors again after changing ghostty theme

[palettes.ghostty]
black = "#1d1f21"
red = "#cc6566"
green = "#b6bd68"
yellow = "#f0c674"
blue = "#82a2be"
magenta = "#b294bb"
cyan = "#8abeb7"
white = "#c4c8c6"
bright_black = "#666666"
bright_red = "#d54e53"
bright_green = "#b9ca4b"
bright_yellow = "#e7c547"
bright_blue = "#7aa6da"
bright_magenta = "#c397d8"
bright_cyan = "#70c0b1"
bright_white = "#eaeaea"
background = "#000000"
foreground = "#ffffff"
