name: Documentation

on:
  push:
    branches:
      - main
      - test/docs
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache mdBook binary
        id: cache-mdbook
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/mdbook
          key: ${{ runner.os }}-mdbook-0.4.52

      - name: Install mdBook
        if: steps.cache-mdbook.outputs.cache-hit != 'true'
        run: cargo install mdbook --version 0.4.52

      - name: Cache mdbook-linkcheck2 binary
        id: cache-linkcheck
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/mdbook-linkcheck2
          key: ${{ runner.os }}-mdbook-linkcheck2-0.9.1

      - name: Install mdbook-linkcheck2
        if: steps.cache-linkcheck.outputs.cache-hit != 'true'
        run: cargo install mdbook-linkcheck2 --version 0.9.1

      - name: Build documentation
        run: |
          cd docs
          mdbook build

      - name: Check links
        run: ./tests/check-links.sh

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./docs/book

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3

  build-check:
    name: Build Check (test/docs)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test/docs'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache mdBook binary
        id: cache-mdbook
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/mdbook
          key: ${{ runner.os }}-mdbook-0.4.52

      - name: Install mdBook
        if: steps.cache-mdbook.outputs.cache-hit != 'true'
        run: cargo install mdbook --version 0.4.52

      - name: Cache mdbook-linkcheck2 binary
        id: cache-linkcheck
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/mdbook-linkcheck2
          key: ${{ runner.os }}-mdbook-linkcheck2-0.9.1

      - name: Install mdbook-linkcheck2
        if: steps.cache-linkcheck.outputs.cache-hit != 'true'
        run: cargo install mdbook-linkcheck2 --version 0.9.1

      - name: Build documentation (verification only)
        run: |
          cd docs
          mdbook build
          echo "Documentation builds successfully on test/docs branch"
          echo "Will deploy when merged to main"

      - name: Check links
        run: ./tests/check-links.sh
